[package]
name = "havenmail-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
sqlx = { version = "0.8", features = ["runtime-tokio", "postgres", "uuid", "chrono", "json"] }
tokio = { workspace = true }
uuid = { version = "1", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
argon2 = "0.5"
password-hash = { version = "0.5", features = ["rand_core"] }
rand_core = { version = "0.6", features = ["std"] }
jsonwebtoken = "9"
totp-rs = { version = "5", features = ["gen_secret", "otpauth"] }
sha2 = "0.10"
thiserror = "1"
tera = "2"
rsa = { version = "0.9", features = ["pem", "sha2"] }
aes-gcm = "0.10"
base64 = "0.22"
hickory-resolver = "0.24"

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
